name: Publish package to NPM
on:
  push:
    paths:
      - "packages/garbo-lib/package.json"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: yarn workspace garbo-lib install

      - name: Check publish status
        id: check
        uses: tehpsalmist/npm-publish-status-action@v1

      - name: Publish if necessary
        if: ${{ steps.check.outputs.exists == '0' }}
        run: yarn workspace garbo-lib npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}